### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by JasonGrace2282** [Pollot/dotfiles#1]
What fonts do you have installed? I'm trying to use your icons (because they look really cool) but it's looking like this:
![image](https://github.com/Pollot/dotfiles/assets/110117391/06a05b1b-de03-45b5-89f6-2c017cc84106)

**Comment by Pollot** [comment]
You can find it in readme.md:

## Nerd Font
I use **FiraCode Nerd Font Mono**. However, you can download any Nerd Font you like from: [Nerd Fonts website](https://www.nerdfonts.com/font-downloads). **Remember to install the mono variant of chosen Nerd Font - icons are not centered in the regular version.**

To quickly install FiraCode and JetBrainsMono Nerd Fonts included in this repository, you can use my script:
```
cd dotfiles/installation

sudo ./fonts.sh
```

**Comment by JasonGrace2282** [comment]
Even after installing both the icons do not render correctly, which is why I was confused.

**Comment by Pollot** [comment]
@JasonGrace2282 which WM are you using? Are you sure that the fonts are installed correctly? Are they accessible in other applications, for example, can you set the Nerd Font in a terminal application?

**Comment by JasonGrace2282** [comment]
I'm on qtile. It turns out I needed a reboot to get the fonts working (quite odd, to be honest. Maybe I should've tried an `fc-cache`).

Might be worth adding to your README? Nice rice btw.
